import os
import shutil

# List of files to delete (exact names as provided)
files_to_delete = [
    "UIAutomationClientSideProviders.dll",
    "UIAutomationProvider.dll",
    "UIAutomationTypes.dll",
    "vcruntime140_cor3.dll",
    "WebView2Loader.dll",
    "WindowsAppRuntime.DeploymentExtensions.OneCore.dll",
    "WindowsAppRuntime.png",
    "WindowsAppSdk.AppxDeploymentExtensions.Desktop.dll",
    "WindowsAppSdk.AppxDeploymentExtensions.Desktop-EventLog-Instrumentation.dll",
    "WindowsBase.dll",
    "WindowsFormsIntegration.dll",
    "workloads.365.json",
    "workloads.json",
    "workloads.lnl.json",
    "workloads.qnn.json",
    "workloads.stx.json",
    "wpfgfx_cor3.dll",
    
    "App.xbf",
    "clretwrc.dll",
    "clrgc.dll",
    "createdump.exe",
    "D3DCompiler_47_cor3.dll",
    "DirectWriteForwarder.dll",
    "DwmSceneI.dll",
    "DWriteCore.dll",
    "Gimme Volumes.pdb",
    "MainWindow.xbf",
    "Microsoft.CSharp.dll",
    "Microsoft.DiaSymReader.Native.amd64.dll",
    "Microsoft.Foundation.winmd",
    "Microsoft.Graphics.Display.dll",
    "Microsoft.Graphics.Imaging.dll",
    "Microsoft.Graphics.Imaging.Projection.dll",
    "Microsoft.Graphics.Imaging.winmd",
    "Microsoft.Graphics.ImagingInternal.winmd",
    "Microsoft.Graphics.Internal.Imaging.winmd",
    "Microsoft.Graphics.winmd",
    "Microsoft.Security.Authentication.OAuth.Projection.dll",
    "Microsoft.Security.Authentication.OAuth.winmd",
    "Microsoft.UI.Text.winmd",
    "Microsoft.UI.winmd",
    "Microsoft.UI.Xaml.Internal.dll",
    "Microsoft.UI.Xaml.Phone.dll",
    "Microsoft.UI.Xaml.winmd",
    "Microsoft.VisualBasic.Core.dll",
    "Microsoft.VisualBasic.dll",
    "Microsoft.VisualBasic.Forms.dll",
    "Microsoft.Web.WebView2.Core.dll",
    "Microsoft.Web.WebView2.Core.Projection.dll",
    "Microsoft.Win32.Registry.AccessControl.dll",
    "Microsoft.Win32.Registry.dll",
    
    "Microsoft.Windows.AI.ContentModerationInternal.winmd",
    "Microsoft.Windows.AI.ContentSafety.dll",
    "Microsoft.Windows.AI.ContentSafety.Projection.dll",
    "Microsoft.Windows.AI.ContentSafety.winmd",
    "Microsoft.Windows.AI.Foundation.winmd",
    "Microsoft.Windows.AI.FoundationInternal.winmd",
    "Microsoft.Windows.AI.GenerativeInternal.winmd",
    "Microsoft.Windows.AI.Imaging.dll",
    "Microsoft.Windows.AI.Imaging.Projection.dll",
    "Microsoft.Windows.AI.Imaging.winmd",
    "Microsoft.Windows.AI.Projection.dll",
    "Microsoft.Windows.AI.Text.dll",
    "Microsoft.Windows.AI.Text.Projection.dll",
    "Microsoft.Windows.AI.Text.winmd",
    "Microsoft.Windows.AI.winmd",
    "Microsoft.Windows.ApplicationModel.Background.Projection.dll",
    "Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.dll",
    "Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.winmd",
    "Microsoft.Windows.ApplicationModel.Background.winmd",
    "Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll",
    "Microsoft.Windows.ApplicationModel.DynamicDependency.winmd",
    "Microsoft.Windows.ApplicationModel.Resources.Projection.dll",
    "Microsoft.Windows.ApplicationModel.Resources.winmd",
    "Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll",
    "Microsoft.Windows.ApplicationModel.WindowsAppRuntime.winmd",
    "Microsoft.Windows.AppLifecycle.Projection.dll",
    "Microsoft.Windows.AppLifecycle.winmd",
    "Microsoft.Windows.AppNotifications.Builder.Projection.dll",
    "Microsoft.Windows.AppNotifications.Builder.winmd",
    "Microsoft.Windows.AppNotifications.Projection.dll",
    "Microsoft.Windows.AppNotifications.winmd",
    "Microsoft.Windows.BadgeNotifications.Projection.dll",
    "Microsoft.Windows.BadgeNotifications.winmd",
    "Microsoft.Windows.Globalization.winmd",
    "Microsoft.Windows.Internal.Vision.winmd",
    "Microsoft.Windows.Management.Deployment.Projection.dll",
    "Microsoft.Windows.Management.Deployment.winmd",
    "Microsoft.Windows.Media.Capture.Projection.dll",
    "Microsoft.Windows.Media.Capture.winmd",
    "Microsoft.Windows.Private.Workloads.SessionManager.winmd",
    "Microsoft.Windows.PrivateCommon.winmd",
    "Microsoft.Windows.PushNotifications.Projection.dll",
    "Microsoft.Windows.PushNotifications.winmd",
    "Microsoft.Windows.Security.AccessControl.Projection.dll",
    "Microsoft.Windows.Security.AccessControl.winmd",
    "Microsoft.Windows.SemanticSearch.winmd",
    "Microsoft.Windows.Storage.Projection.dll",
    "Microsoft.Windows.Storage.winmd",
    "Microsoft.Windows.System.Power.Projection.dll",
    "Microsoft.Windows.System.Power.winmd",
    "Microsoft.Windows.System.Projection.dll",
    "Microsoft.Windows.System.winmd",
    "Microsoft.Windows.Vision.winmd",
    "Microsoft.Windows.VisionInternal.winmd",
    "Microsoft.Windows.Widgets.dll",
    "Microsoft.Windows.Widgets.Projection.dll",
    "Microsoft.Windows.Widgets.winmd",
    "Microsoft.Windows.Workloads.dll",
    "Microsoft.Windows.Workloads.Resources.dll",
    "Microsoft.Windows.Workloads.Resources_ec.dll",
    "Microsoft.Windows.Workloads.winmd",
    "Microsoft.WindowsAppRuntime.Bootstrap.dll",
    "Microsoft.WindowsAppRuntime.Bootstrap.Net.dll",
    "Microsoft.WindowsAppRuntime.Insights.Resource.dll",
    "mscordaccore.dll",
    "mscordaccore_amd64_amd64_8.0.1625.21506.dll",
    "mscordbi.dll",
    "mscorlib.dll",
    "mscorrc.dll",
    "msquic.dll",
    "NAudio.Asio.dll",
    "NAudio.Core.dll",
    "NAudio.dll",
    "NAudio.Midi.dll",
    "NAudio.WinForms.dll",
    "NAudio.WinMM.dll",
    "PenImc_cor3.dll",
    "PresentationCore.dll",
    "PresentationFramework.Aero.dll",
    "PresentationFramework.Aero2.dll",
    "PresentationFramework.AeroLite.dll",
    "PresentationFramework.Classic.dll",
    "PresentationFramework.dll",
    "PresentationFramework.Luna.dll",
    "PresentationFramework.Royale.dll",
    "PresentationFramework-SystemCore.dll",
    "PresentationFramework-SystemData.dll",
    "PresentationFramework-SystemDrawing.dll",
    "PresentationFramework-SystemXml.dll",
    "PresentationFramework-SystemXmlLinq.dll",
    "PresentationNative_cor3.dll",
    "PresentationUI.dll",
    "PushNotificationsLongRunningTask.ProxyStub.dll",
    "ReachFramework.dll",
    "RestartAgent.exe",
    "SessionHandleIPCProxyStub.dll",
    "System.AppContext.dll",
    "System.Buffers.dll",
    "System.CodeDom.dll",
    "System.Collections.Immutable.dll",
    "System.Collections.NonGeneric.dll",
    
    "System.ComponentModel.Annotations.dll",
    "System.ComponentModel.DataAnnotations.dll",
    
    
    "System.Configuration.ConfigurationManager.dll",
    "System.Configuration.dll",
    "System.Console.dll",
    "System.Core.dll",
    "System.Data.Common.dll",
    "System.Data.DataSetExtensions.dll",
    "System.Data.dll",
    "System.Design.dll",
    "System.Diagnostics.Contracts.dll",
    "System.Diagnostics.Debug.dll",
    "System.Diagnostics.DiagnosticSource.dll",
    "System.Diagnostics.EventLog.dll",
    "System.Diagnostics.EventLog.Messages.dll",
    "System.Diagnostics.FileVersionInfo.dll",
    "System.Diagnostics.PerformanceCounter.dll",
    
    "System.Diagnostics.TextWriterTraceListener.dll",
    "System.Diagnostics.Tools.dll",

    "System.Diagnostics.Tracing.dll",
    "System.DirectoryServices.dll",
    "System.dll",
    
    "System.Drawing.Design.dll",
    "System.Drawing.dll",
    
    "System.Dynamic.Runtime.dll",
    "System.Formats.Asn1.dll",
    "System.Formats.Tar.dll",
    "System.Globalization.Calendars.dll",
    "System.Globalization.dll",
    "System.Globalization.Extensions.dll",
    "System.IO.Compression.Brotli.dll",
    "System.IO.Compression.dll",
    "System.IO.Compression.FileSystem.dll",
    "System.IO.Compression.Native.dll",
    "System.IO.Compression.ZipFile.dll",
    "System.IO.dll",
    "System.IO.FileSystem.AccessControl.dll",
    "System.IO.FileSystem.dll",
    "System.IO.FileSystem.DriveInfo.dll",
    "System.IO.FileSystem.Primitives.dll",
    "System.IO.FileSystem.Watcher.dll",
    "System.IO.IsolatedStorage.dll",
    "System.IO.MemoryMappedFiles.dll",
    "System.IO.Packaging.dll",
    "System.IO.Pipes.AccessControl.dll",
    "System.IO.Pipes.dll",
    "System.IO.UnmanagedMemoryStream.dll",
    
    "System.Linq.Parallel.dll",
    "System.Linq.Queryable.dll",
    "System.Net.dll",
    "System.Net.Http.dll",
    "System.Net.Http.Json.dll",
    "System.Net.HttpListener.dll",
    "System.Net.Mail.dll",
    "System.Net.NameResolution.dll",
    "System.Net.NetworkInformation.dll",
    "System.Net.Ping.dll",
    "System.Net.Primitives.dll",
    "System.Net.Quic.dll",
    "System.Net.Requests.dll",
    "System.Net.Security.dll",
    "System.Net.ServicePoint.dll",
    "System.Net.Sockets.dll",
    "System.Net.WebClient.dll",
    "System.Net.WebHeaderCollection.dll",
    "System.Net.WebProxy.dll",
    "System.Net.WebSockets.Client.dll",
    "System.Net.WebSockets.dll",
    "System.Numerics.dll",
    "System.Printing.dll",
    "System.Private.DataContractSerialization.dll",
    "System.Private.Xml.dll",
    "System.Private.Xml.Linq.dll",
    "System.Reflection.DispatchProxy.dll",
    "System.Reflection.dll",
    "System.Reflection.Emit.ILGeneration.dll",
    "System.Reflection.Emit.Lightweight.dll",
    "System.Reflection.Extensions.dll",
    "System.Reflection.Metadata.dll",
    "System.Reflection.Primitives.dll",
    "System.Reflection.TypeExtensions.dll",
    "System.Resources.Extensions.dll",
    "System.Resources.Reader.dll",
    "System.Resources.ResourceManager.dll",
    "System.Resources.Writer.dll",
    "System.Runtime.CompilerServices.VisualC.dll",
    "System.Runtime.Extensions.dll",
    "System.Runtime.Handles.dll",
    "System.Runtime.InteropServices.JavaScript.dll",
    "System.Runtime.InteropServices.RuntimeInformation.dll",
    "System.Runtime.Intrinsics.dll",
    
    "System.Runtime.Numerics.dll",
    "System.Runtime.Serialization.dll",
    "System.Runtime.Serialization.Formatters.dll",
    "System.Runtime.Serialization.Json.dll",
    "System.Runtime.Serialization.Primitives.dll",
    "System.Runtime.Serialization.Xml.dll",
    "System.Security.AccessControl.dll",
    "System.Security.Claims.dll",
    "System.Security.Cryptography.Algorithms.dll",
    "System.Security.Cryptography.Cng.dll",
    "System.Security.Cryptography.Csp.dll",
    "System.Security.Cryptography.Encoding.dll",
    "System.Security.Cryptography.OpenSsl.dll",
    "System.Security.Cryptography.Pkcs.dll",
    "System.Security.Cryptography.Primitives.dll",
    "System.Security.Cryptography.ProtectedData.dll",
    "System.Security.Cryptography.X509Certificates.dll",
    "System.Security.Cryptography.Xml.dll",
    "System.Security.dll",
    "System.Security.Permissions.dll",
    "System.Security.Principal.dll",
    "System.Security.Principal.Windows.dll",
    "System.Security.SecureString.dll",
    "System.ServiceModel.Web.dll",
    "System.ServiceProcess.dll",
    "System.Text.Encoding.CodePages.dll",
    "System.Text.Encoding.dll",
    "System.Text.Encoding.Extensions.dll",
    "System.Text.Encodings.Web.dll",
    "System.Text.Json.dll",
    "System.Text.RegularExpressions.dll",
    "System.Threading.AccessControl.dll",
    "System.Threading.Channels.dll",
    "System.Threading.Overlapped.dll",
    "System.Threading.Tasks.Dataflow.dll",
    "System.Threading.Tasks.dll",
    "System.Threading.Tasks.Extensions.dll",
    "System.Threading.Tasks.Parallel.dll",
    
    "System.Threading.ThreadPool.dll",
    "System.Threading.Timer.dll",
    "System.Transactions.dll",
    "System.Transactions.Local.dll",
    "System.ValueTuple.dll",
    "System.Web.dll",
    "System.Web.HttpUtility.dll",
    "System.Windows.Controls.Ribbon.dll",
    "System.Windows.dll",
    "System.Windows.Extensions.dll",
    "System.Windows.Forms.Design.dll",
    "System.Windows.Forms.Design.Editors.dll",
    "System.Windows.Forms.Design.resources.dll",
    
    
    "System.Windows.Forms.Primitives.resources.dll",
    "System.Windows.Forms.resources.dll",
    "System.Windows.Input.Manipulations.dll",
    "System.Windows.Presentation.dll",
    "System.Xaml.dll",
    "System.Xml.dll",
    "System.Xml.Linq.dll",
    "System.Xml.ReaderWriter.dll",
    "System.Xml.Serialization.dll",
    "System.Xml.XDocument.dll",
    "System.Xml.XmlDocument.dll",
    "System.Xml.XmlSerializer.dll",
    "System.Xml.XPath.dll",
    "System.Xml.XPath.XDocument.dll",
    "UIAutomationClient.dll"
]
# List of folders to delete
folders_to_delete = [
    "Assets",
    "zh-TW",
    "af-ZA",
    "am-ET",
    "ar-SA",
    "as-IN",
    "az-Latn-AZ",
    "bg-BG",
    "bn-IN",
    "bs-Latn-BA",
    "ca-ES",
    "ca-Es-VALENCIA",
    "cs",
    "cs-CZ",
    "cy-GB",
    "da-DK",
    "de",
    "de-DE",
    "el-GR",
    "en-GB",
    "es",
    "es-ES",
    "es-MX",
    "et-EE",
    "eu-ES",
    "fa-IR",
    "fi-FI",
    "fil-PH",
    "fr",
    "fr-CA",
    "fr-FR",
    "ga-IE",
    "gd-gb",
    "gl-ES",
    "gu-IN",
    "he-IL",
    "hi-IN",
    "hr-HR",
    "hu-HU",
    "hy-AM",
    "id-ID",
    "is-IS",
    "it",
    "it-IT",
    "ja",
    "ja-JP",
    "ka-GE",
    "kk-KZ",
    "km-KH",
    "kn-IN",
    "ko",
    "kok-IN",
    "ko-KR",
    "lb-LU",
    "lo-LA",
    "lt-LT",
    "lv-LV",
    
    "mi-NZ",
    "mk-MK",
    "ml-IN",
    "mr-IN",
    "ms-MY",
    "mt-MT",
    "nb-NO",
    "ne-NP",
    "nl-NL",
    "nn-NO",
    "NpuDetect",
    "or-IN",
    "pa-IN",
    "pl",
    "pl-PL",
    "pt-BR",
    "pt-PT",
    "quz-PE",
    "ro-RO",
    "ru",
    "ru-RU",
    "sk-SK",
    "sl-SI",
    "sq-AL",
    "sr-Cyrl-BA",
    "sr-Cyrl-RS",
    "sr-Latn-RS",
    "sv-SE",
    "ta-IN",
    "te-IN",
    "th-TH",
    "tr",
    "tr-TR",
    "tt-RU",
    "ug-CN",
    "uk-UA",
    "ur-PK",
    "uz-Latn-UZ",
    "vi-VN",
    "zh-CN",
    "zh-Hans",
    "zh-Hant"
]

def delete_files():
    deleted_file_count = 0
    failed_file_count = 0
    
    print("Deleting files...\n")
    for file_name in files_to_delete:
        try:
            if os.path.exists(file_name):
                os.remove(file_name)
                print(f"Deleted file: {file_name}")
                deleted_file_count += 1
            else:
                print(f"File not found: {file_name}")
        except Exception as e:
            print(f"Failed to delete file {file_name}: {str(e)}")
            failed_file_count += 1
    
    return deleted_file_count, failed_file_count

def delete_folders():
    deleted_folder_count = 0
    failed_folder_count = 0
    
    print("\nDeleting folders...\n")
    for folder_name in folders_to_delete:
        try:
            if os.path.exists(folder_name) and os.path.isdir(folder_name):
                shutil.rmtree(folder_name)
                print(f"Deleted folder: {folder_name}")
                deleted_folder_count += 1
            else:
                print(f"Folder not found: {folder_name}")
        except Exception as e:
            print(f"Failed to delete folder {folder_name}: {str(e)}")
            failed_folder_count += 1
    
    return deleted_folder_count, failed_folder_count

if __name__ == "__main__":
    print("Starting cleanup process...")
    
    files_deleted, files_failed = delete_files()
    folders_deleted, folders_failed = delete_folders()
    
    print("\nCleanup summary:")
    print(f"Files successfully deleted: {files_deleted}")
    print(f"Files failed to delete: {files_failed}")
    print(f"Folders successfully deleted: {folders_deleted}")
    print(f"Folders failed to delete: {folders_failed}")
    print(f"\nTotal files processed: {len(files_to_delete)}")
    print(f"Total folders processed: {len(folders_to_delete)}")
